version: '3.1'

services:
  db:
  #  command: pg_ctl -D /var/lib/postgresql/data -l logfile start
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: holger
      POSTGRES_PASSWORD: heidelbert
    volumes:
      - $PWD/data:/var/lib/postgresql/data

    ports:
      - 5432:5432
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      RAILS_ENV: production
      DATABASE_CLEANER_ALLOW_PRODUCTION: "true"
      RAILS_SERVE_STATIC_FILES: "true"
      SMTP_ADDRESS: "smtp.gmail.com"
      SMTP_PORT: "587"
      DOMAIN: "domain.of.sender.net"
      SMTP_USER: "herr.holger.kraus@googlemail.com"
      SMTP_PASSWORD: "jvcuxaflveohulgy"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db